### ISSUE TITLE
Links fails to compile with OCaml 4.07

### ISSUE THREAD

**Issue by dhil** [links-lang/links#407]
I get a compilation error when using OCaml 4.07 to build Links.
```shell
$ dune build --only-packages links,links-postgresql -j 1 --profile=development @install
      ocamlc core/.links.objs/closures.{cmi,cmo,cmt} (exit 2)
(cd _build/default && $HOME/.opam/4.07.0/bin/ocamlc.opt -w -40 -safe-string -dtypes -w Ae-44-45-60 -g -cclib -lunix -thread -g -bin-annot -I core/.links.objs -I $HOME/.opam/4.07.0/lib/ANSITerminal -I $HOME/.opam/4.07.0/lib/astring -I $HOME/.opam/4.07.0/lib/base -I $HOME/.opam/4.07.0/lib/base/caml -I $HOME/.opam/4.07.0/lib/base/shadow_stdlib -I $HOME/.opam/4.07.0/lib/base64 -I $HOME/.opam/4.07.0/lib/biniou -I $HOME/.opam/4.07.0/lib/bytes -I $HOME/.opam/4.07.0/lib/cohttp -I $HOME/.opam/4.07.0/lib/cohttp-lwt -I $HOME/.opam/4.07.0/lib/cohttp-lwt-unix -I $HOME/.opam/4.07.0/lib/conduit -I $HOME/.opam/4.07.0/lib/conduit-lwt -I $HOME/.opam/4.07.0/lib/conduit-lwt-unix -I $HOME/.opam/4.07.0/lib/easy-format -I $HOME/.opam/4.07.0/lib/fieldslib -I $HOME/.opam/4.07.0/lib/findlib -I $HOME/.opam/4.07.0/lib/fmt -I $HOME/.opam/4.07.0/lib/ipaddr -I $HOME/.opam/4.07.0/lib/ipaddr/unix -I $HOME/.opam/4.07.0/lib/linenoise -I $HOME/.opam/4.07.0/lib/logs -I $HOME/.opam/4.07.0/lib/lwt -I $HOME/.opam/4.07.0/lib/lwt_ssl -I $HOME/.opam/4.07.0/lib/magic-mime -I $HOME/.opam/4.07.0/lib/ocaml/threads -I $HOME/.opam/4.07.0/lib/ocplib-endian -I $HOME/.opam/4.07.0/lib/parsexp -I $HOME/.opam/4.07.0/lib/ppx_deriving -I $HOME/.opam/4.07.0/lib/ppx_deriving_yojson -I $HOME/.opam/4.07.0/lib/ppx_sexp_conv/runtime-lib -I $HOME/.opam/4.07.0/lib/re -I $HOME/.opam/4.07.0/lib/re/emacs -I $HOME/.opam/4.07.0/lib/re/posix -I $HOME/.opam/4.07.0/lib/result -I $HOME/.opam/4.07.0/lib/safepass -I $HOME/.opam/4.07.0/lib/sexplib -I $HOME/.opam/4.07.0/lib/sexplib0 -I $HOME/.opam/4.07.0/lib/ssl -I $HOME/.opam/4.07.0/lib/stringext -I $HOME/.opam/4.07.0/lib/uchar -I $HOME/.opam/4.07.0/lib/uri -I $HOME/.opam/4.07.0/lib/uri/services -I $HOME/.opam/4.07.0/lib/websocket -I $HOME/.opam/4.07.0/lib/websocket-lwt/cohttp -I $HOME/.opam/4.07.0/lib/yojson -no-alias-deps -o core/.links.objs/closures.cmo -c -impl core/closures.pp.ml)
Fatal error: exception Ctype.Unify(_)
```
However, the build completes when I use OCaml 4.06.1. It seems to throw during compilation of `closures.ml`, so this regression might have been introduced by [ad6d594](4d6d59420c7277c3084df5924d603d0a1cc52349).

**Comment by yallop** [comment]
This looks like an OCaml bug.  It'd be good to report it [upstream](https://caml.inria.fr/mantis/bug_report_page.php), ideally with a minimal reproduction case.

**Comment by frank-emrich** [comment]
Funny, I stumbled over this exact problem yesterday. The problem wasn't introduced by 4d6d5942, but it is located in line 476 of closures.ml:
```(* The following type annotation is necessary as of OCaml
             4.07.0. Is this a bug in OCaml? *)
          let zb, (o : 'self) =```

Without the 'self type annotation, the problem turns into a type error instead of the compiler crashing. The comment and type annotation was introduced by @slindley, so I guess it did work with 4.07.0 at some point?

**Comment by dhil** [comment]
The problem persists with OCaml 4.07.1. I haven't had time to reproduce a minimal example yet.

**Comment by slindley** [comment]
Of course the problem *was* introduced by 4d6d594! The problem was the call to o#binder inside the body of the let with the type annotation on it (line 493 before my fix). The workaround (4d3a6d5f182) lifts that into another function. The type annotation is necessary to suppress the type error.

Someone should now isolate the OCaml compiler bug with a minimal example and report it!

**Comment by slindley** [comment]
I've now isolated the original problem and reported it as an OCaml bug: https://caml.inria.fr/mantis/view.php?id=7865

**Comment by frank-emrich** [comment]
I have now verified that the compiler error that occured before Sam's fix has been fixed in the 4.08 trunk
